// <auto-generated />
namespace DiscStore.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ModelUpdateForDescription2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModelUpdateForDescription2));
        
        string IMigrationMetadata.Id
        {
            get { return "201805041526328_ModelUpdateForDescription2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
